package edu.carleton.comp4905.carcassonne.common;

public enum EventType {
	UNKNOWN,
	KEEP_ALIVE,
	JOIN_REQUEST,
	JOIN_REPLY,
	QUIT_REQUEST,
	QUIT_REPLY,
	START_REQUEST,
	START_REPLY,
	SEND_TILE_REQUEST,
	SEND_TILE_REPLY,
	SCORE_UPDATE_REQUEST,
	SCORE_UPDATE_REPLY,
	FOLLOWER_UPDATE_REQUEST,
	FOLLOWER_UPDATE_REPLY,
	END_GAME_REQUEST,
	END_GAME_REPLY,
	START_TURN_REQUEST,
	START_TURN_REPLY,
	END_TURN_REQUEST,
	END_TURN_REPLY
}
