// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package edu.carleton.comp4905.carcassonne.common;

public final class EventMessage {
  private EventMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 eventType = 1;
    /**
     * <code>required int32 eventType = 1;</code>
     */
    boolean hasEventType();
    /**
     * <code>required int32 eventType = 1;</code>
     */
    int getEventType();

    // required string playerName = 2;
    /**
     * <code>required string playerName = 2;</code>
     */
    boolean hasPlayerName();
    /**
     * <code>required string playerName = 2;</code>
     */
    java.lang.String getPlayerName();
    /**
     * <code>required string playerName = 2;</code>
     */
    com.google.protobuf.ByteString
        getPlayerNameBytes();

    // optional bytes connection = 3;
    /**
     * <code>optional bytes connection = 3;</code>
     */
    boolean hasConnection();
    /**
     * <code>optional bytes connection = 3;</code>
     */
    com.google.protobuf.ByteString getConnection();

    // optional string address = 4;
    /**
     * <code>optional string address = 4;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 4;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 4;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    // optional int32 port = 5;
    /**
     * <code>optional int32 port = 5;</code>
     */
    boolean hasPort();
    /**
     * <code>optional int32 port = 5;</code>
     */
    int getPort();

    // optional int32 numOfPlayers = 6;
    /**
     * <code>optional int32 numOfPlayers = 6;</code>
     */
    boolean hasNumOfPlayers();
    /**
     * <code>optional int32 numOfPlayers = 6;</code>
     */
    int getNumOfPlayers();

    // optional bool success = 7;
    /**
     * <code>optional bool success = 7;</code>
     */
    boolean hasSuccess();
    /**
     * <code>optional bool success = 7;</code>
     */
    boolean getSuccess();

    // optional string message = 8;
    /**
     * <code>optional string message = 8;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 8;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 8;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    // repeated bool statuses = 9;
    /**
     * <code>repeated bool statuses = 9;</code>
     */
    java.util.List<java.lang.Boolean> getStatusesList();
    /**
     * <code>repeated bool statuses = 9;</code>
     */
    int getStatusesCount();
    /**
     * <code>repeated bool statuses = 9;</code>
     */
    boolean getStatuses(int index);

    // repeated string names = 10;
    /**
     * <code>repeated string names = 10;</code>
     */
    java.util.List<java.lang.String>
    getNamesList();
    /**
     * <code>repeated string names = 10;</code>
     */
    int getNamesCount();
    /**
     * <code>repeated string names = 10;</code>
     */
    java.lang.String getNames(int index);
    /**
     * <code>repeated string names = 10;</code>
     */
    com.google.protobuf.ByteString
        getNamesBytes(int index);

    // optional bool finished = 11;
    /**
     * <code>optional bool finished = 11;</code>
     */
    boolean hasFinished();
    /**
     * <code>optional bool finished = 11;</code>
     */
    boolean getFinished();

    // optional bool gameInProgress = 12;
    /**
     * <code>optional bool gameInProgress = 12;</code>
     */
    boolean hasGameInProgress();
    /**
     * <code>optional bool gameInProgress = 12;</code>
     */
    boolean getGameInProgress();

    // optional string tile = 13;
    /**
     * <code>optional string tile = 13;</code>
     */
    boolean hasTile();
    /**
     * <code>optional string tile = 13;</code>
     */
    java.lang.String getTile();
    /**
     * <code>optional string tile = 13;</code>
     */
    com.google.protobuf.ByteString
        getTileBytes();

    // optional int32 row = 14;
    /**
     * <code>optional int32 row = 14;</code>
     */
    boolean hasRow();
    /**
     * <code>optional int32 row = 14;</code>
     */
    int getRow();

    // optional int32 column = 15;
    /**
     * <code>optional int32 column = 15;</code>
     */
    boolean hasColumn();
    /**
     * <code>optional int32 column = 15;</code>
     */
    int getColumn();

    // optional int32 rotation = 16;
    /**
     * <code>optional int32 rotation = 16;</code>
     */
    boolean hasRotation();
    /**
     * <code>optional int32 rotation = 16;</code>
     */
    int getRotation();

    // optional int32 meeple = 17;
    /**
     * <code>optional int32 meeple = 17;</code>
     */
    boolean hasMeeple();
    /**
     * <code>optional int32 meeple = 17;</code>
     */
    int getMeeple();

    // optional int32 position = 18;
    /**
     * <code>optional int32 position = 18;</code>
     */
    boolean hasPosition();
    /**
     * <code>optional int32 position = 18;</code>
     */
    int getPosition();

    // optional bool shield = 19;
    /**
     * <code>optional bool shield = 19;</code>
     */
    boolean hasShield();
    /**
     * <code>optional bool shield = 19;</code>
     */
    boolean getShield();

    // optional string target = 20;
    /**
     * <code>optional string target = 20;</code>
     */
    boolean hasTarget();
    /**
     * <code>optional string target = 20;</code>
     */
    java.lang.String getTarget();
    /**
     * <code>optional string target = 20;</code>
     */
    com.google.protobuf.ByteString
        getTargetBytes();

    // optional int32 points = 21;
    /**
     * <code>optional int32 points = 21;</code>
     */
    boolean hasPoints();
    /**
     * <code>optional int32 points = 21;</code>
     */
    int getPoints();

    // optional int32 followers = 22;
    /**
     * <code>optional int32 followers = 22;</code>
     */
    boolean hasFollowers();
    /**
     * <code>optional int32 followers = 22;</code>
     */
    int getFollowers();

    // optional int32 targetIndex = 23;
    /**
     * <code>optional int32 targetIndex = 23;</code>
     */
    boolean hasTargetIndex();
    /**
     * <code>optional int32 targetIndex = 23;</code>
     */
    int getTargetIndex();
  }
  /**
   * Protobuf type {@code edu.carleton.comp4905.carcassonne.common.Event}
   */
  public static final class Event extends
      com.google.protobuf.GeneratedMessage
      implements EventOrBuilder {
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Event(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Event defaultInstance;
    public static Event getDefaultInstance() {
      return defaultInstance;
    }

    @Override
	public Event getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              eventType_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              playerName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              connection_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              address_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              port_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              numOfPlayers_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              success_ = input.readBool();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              message_ = input.readBytes();
              break;
            }
            case 72: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                statuses_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000100;
              }
              statuses_.add(input.readBool());
              break;
            }
            case 74: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100) && input.getBytesUntilLimit() > 0) {
                statuses_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000100;
              }
              while (input.getBytesUntilLimit() > 0) {
                statuses_.add(input.readBool());
              }
              input.popLimit(limit);
              break;
            }
            case 82: {
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
                names_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000200;
              }
              names_.add(input.readBytes());
              break;
            }
            case 88: {
              bitField0_ |= 0x00000100;
              finished_ = input.readBool();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000200;
              gameInProgress_ = input.readBool();
              break;
            }
            case 106: {
              bitField0_ |= 0x00000400;
              tile_ = input.readBytes();
              break;
            }
            case 112: {
              bitField0_ |= 0x00000800;
              row_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00001000;
              column_ = input.readInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00002000;
              rotation_ = input.readInt32();
              break;
            }
            case 136: {
              bitField0_ |= 0x00004000;
              meeple_ = input.readInt32();
              break;
            }
            case 144: {
              bitField0_ |= 0x00008000;
              position_ = input.readInt32();
              break;
            }
            case 152: {
              bitField0_ |= 0x00010000;
              shield_ = input.readBool();
              break;
            }
            case 162: {
              bitField0_ |= 0x00020000;
              target_ = input.readBytes();
              break;
            }
            case 168: {
              bitField0_ |= 0x00040000;
              points_ = input.readInt32();
              break;
            }
            case 176: {
              bitField0_ |= 0x00080000;
              followers_ = input.readInt32();
              break;
            }
            case 184: {
              bitField0_ |= 0x00100000;
              targetIndex_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          statuses_ = java.util.Collections.unmodifiableList(statuses_);
        }
        if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
          names_ = new com.google.protobuf.UnmodifiableLazyStringList(names_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.carleton.comp4905.carcassonne.common.EventMessage.internal_static_edu_carleton_comp4905_carcassonne_common_Event_descriptor;
    }

    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.carleton.comp4905.carcassonne.common.EventMessage.internal_static_edu_carleton_comp4905_carcassonne_common_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.carleton.comp4905.carcassonne.common.EventMessage.Event.class, edu.carleton.comp4905.carcassonne.common.EventMessage.Event.Builder.class);
    }

    public static com.google.protobuf.Parser<Event> PARSER =
        new com.google.protobuf.AbstractParser<Event>() {
      @Override
	public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Event(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 eventType = 1;
    public static final int EVENTTYPE_FIELD_NUMBER = 1;
    private int eventType_;
    /**
     * <code>required int32 eventType = 1;</code>
     */
    @Override
	public boolean hasEventType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 eventType = 1;</code>
     */
    @Override
	public int getEventType() {
      return eventType_;
    }

    // required string playerName = 2;
    public static final int PLAYERNAME_FIELD_NUMBER = 2;
    private java.lang.Object playerName_;
    /**
     * <code>required string playerName = 2;</code>
     */
    @Override
	public boolean hasPlayerName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string playerName = 2;</code>
     */
    @Override
	public java.lang.String getPlayerName() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          playerName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string playerName = 2;</code>
     */
    @Override
	public com.google.protobuf.ByteString
        getPlayerNameBytes() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes connection = 3;
    public static final int CONNECTION_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString connection_;
    /**
     * <code>optional bytes connection = 3;</code>
     */
    @Override
	public boolean hasConnection() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes connection = 3;</code>
     */
    @Override
	public com.google.protobuf.ByteString getConnection() {
      return connection_;
    }

    // optional string address = 4;
    public static final int ADDRESS_FIELD_NUMBER = 4;
    private java.lang.Object address_;
    /**
     * <code>optional string address = 4;</code>
     */
    @Override
	public boolean hasAddress() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string address = 4;</code>
     */
    @Override
	public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 4;</code>
     */
    @Override
	public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 port = 5;
    public static final int PORT_FIELD_NUMBER = 5;
    private int port_;
    /**
     * <code>optional int32 port = 5;</code>
     */
    @Override
	public boolean hasPort() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 port = 5;</code>
     */
    @Override
	public int getPort() {
      return port_;
    }

    // optional int32 numOfPlayers = 6;
    public static final int NUMOFPLAYERS_FIELD_NUMBER = 6;
    private int numOfPlayers_;
    /**
     * <code>optional int32 numOfPlayers = 6;</code>
     */
    @Override
	public boolean hasNumOfPlayers() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 numOfPlayers = 6;</code>
     */
    @Override
	public int getNumOfPlayers() {
      return numOfPlayers_;
    }

    // optional bool success = 7;
    public static final int SUCCESS_FIELD_NUMBER = 7;
    private boolean success_;
    /**
     * <code>optional bool success = 7;</code>
     */
    @Override
	public boolean hasSuccess() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool success = 7;</code>
     */
    @Override
	public boolean getSuccess() {
      return success_;
    }

    // optional string message = 8;
    public static final int MESSAGE_FIELD_NUMBER = 8;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 8;</code>
     */
    @Override
	public boolean hasMessage() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string message = 8;</code>
     */
    @Override
	public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 8;</code>
     */
    @Override
	public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated bool statuses = 9;
    public static final int STATUSES_FIELD_NUMBER = 9;
    private java.util.List<java.lang.Boolean> statuses_;
    /**
     * <code>repeated bool statuses = 9;</code>
     */
    @Override
	public java.util.List<java.lang.Boolean>
        getStatusesList() {
      return statuses_;
    }
    /**
     * <code>repeated bool statuses = 9;</code>
     */
    @Override
	public int getStatusesCount() {
      return statuses_.size();
    }
    /**
     * <code>repeated bool statuses = 9;</code>
     */
    @Override
	public boolean getStatuses(int index) {
      return statuses_.get(index);
    }

    // repeated string names = 10;
    public static final int NAMES_FIELD_NUMBER = 10;
    private com.google.protobuf.LazyStringList names_;
    /**
     * <code>repeated string names = 10;</code>
     */
    @Override
	public java.util.List<java.lang.String>
        getNamesList() {
      return names_;
    }
    /**
     * <code>repeated string names = 10;</code>
     */
    @Override
	public int getNamesCount() {
      return names_.size();
    }
    /**
     * <code>repeated string names = 10;</code>
     */
    @Override
	public java.lang.String getNames(int index) {
      return names_.get(index);
    }
    /**
     * <code>repeated string names = 10;</code>
     */
    @Override
	public com.google.protobuf.ByteString
        getNamesBytes(int index) {
      return names_.getByteString(index);
    }

    // optional bool finished = 11;
    public static final int FINISHED_FIELD_NUMBER = 11;
    private boolean finished_;
    /**
     * <code>optional bool finished = 11;</code>
     */
    @Override
	public boolean hasFinished() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bool finished = 11;</code>
     */
    @Override
	public boolean getFinished() {
      return finished_;
    }

    // optional bool gameInProgress = 12;
    public static final int GAMEINPROGRESS_FIELD_NUMBER = 12;
    private boolean gameInProgress_;
    /**
     * <code>optional bool gameInProgress = 12;</code>
     */
    @Override
	public boolean hasGameInProgress() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional bool gameInProgress = 12;</code>
     */
    @Override
	public boolean getGameInProgress() {
      return gameInProgress_;
    }

    // optional string tile = 13;
    public static final int TILE_FIELD_NUMBER = 13;
    private java.lang.Object tile_;
    /**
     * <code>optional string tile = 13;</code>
     */
    @Override
	public boolean hasTile() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string tile = 13;</code>
     */
    @Override
	public java.lang.String getTile() {
      java.lang.Object ref = tile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tile_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tile = 13;</code>
     */
    @Override
	public com.google.protobuf.ByteString
        getTileBytes() {
      java.lang.Object ref = tile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 row = 14;
    public static final int ROW_FIELD_NUMBER = 14;
    private int row_;
    /**
     * <code>optional int32 row = 14;</code>
     */
    @Override
	public boolean hasRow() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int32 row = 14;</code>
     */
    @Override
	public int getRow() {
      return row_;
    }

    // optional int32 column = 15;
    public static final int COLUMN_FIELD_NUMBER = 15;
    private int column_;
    /**
     * <code>optional int32 column = 15;</code>
     */
    @Override
	public boolean hasColumn() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int32 column = 15;</code>
     */
    @Override
	public int getColumn() {
      return column_;
    }

    // optional int32 rotation = 16;
    public static final int ROTATION_FIELD_NUMBER = 16;
    private int rotation_;
    /**
     * <code>optional int32 rotation = 16;</code>
     */
    @Override
	public boolean hasRotation() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional int32 rotation = 16;</code>
     */
    @Override
	public int getRotation() {
      return rotation_;
    }

    // optional int32 meeple = 17;
    public static final int MEEPLE_FIELD_NUMBER = 17;
    private int meeple_;
    /**
     * <code>optional int32 meeple = 17;</code>
     */
    @Override
	public boolean hasMeeple() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional int32 meeple = 17;</code>
     */
    @Override
	public int getMeeple() {
      return meeple_;
    }

    // optional int32 position = 18;
    public static final int POSITION_FIELD_NUMBER = 18;
    private int position_;
    /**
     * <code>optional int32 position = 18;</code>
     */
    @Override
	public boolean hasPosition() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional int32 position = 18;</code>
     */
    @Override
	public int getPosition() {
      return position_;
    }

    // optional bool shield = 19;
    public static final int SHIELD_FIELD_NUMBER = 19;
    private boolean shield_;
    /**
     * <code>optional bool shield = 19;</code>
     */
    @Override
	public boolean hasShield() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional bool shield = 19;</code>
     */
    @Override
	public boolean getShield() {
      return shield_;
    }

    // optional string target = 20;
    public static final int TARGET_FIELD_NUMBER = 20;
    private java.lang.Object target_;
    /**
     * <code>optional string target = 20;</code>
     */
    @Override
	public boolean hasTarget() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <code>optional string target = 20;</code>
     */
    @Override
	public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          target_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string target = 20;</code>
     */
    @Override
	public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 points = 21;
    public static final int POINTS_FIELD_NUMBER = 21;
    private int points_;
    /**
     * <code>optional int32 points = 21;</code>
     */
    @Override
	public boolean hasPoints() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    /**
     * <code>optional int32 points = 21;</code>
     */
    @Override
	public int getPoints() {
      return points_;
    }

    // optional int32 followers = 22;
    public static final int FOLLOWERS_FIELD_NUMBER = 22;
    private int followers_;
    /**
     * <code>optional int32 followers = 22;</code>
     */
    @Override
	public boolean hasFollowers() {
      return ((bitField0_ & 0x00080000) == 0x00080000);
    }
    /**
     * <code>optional int32 followers = 22;</code>
     */
    @Override
	public int getFollowers() {
      return followers_;
    }

    // optional int32 targetIndex = 23;
    public static final int TARGETINDEX_FIELD_NUMBER = 23;
    private int targetIndex_;
    /**
     * <code>optional int32 targetIndex = 23;</code>
     */
    @Override
	public boolean hasTargetIndex() {
      return ((bitField0_ & 0x00100000) == 0x00100000);
    }
    /**
     * <code>optional int32 targetIndex = 23;</code>
     */
    @Override
	public int getTargetIndex() {
      return targetIndex_;
    }

    private void initFields() {
      eventType_ = 0;
      playerName_ = "";
      connection_ = com.google.protobuf.ByteString.EMPTY;
      address_ = "";
      port_ = 0;
      numOfPlayers_ = 0;
      success_ = false;
      message_ = "";
      statuses_ = java.util.Collections.emptyList();
      names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      finished_ = false;
      gameInProgress_ = false;
      tile_ = "";
      row_ = 0;
      column_ = 0;
      rotation_ = 0;
      meeple_ = 0;
      position_ = 0;
      shield_ = false;
      target_ = "";
      points_ = 0;
      followers_ = 0;
      targetIndex_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasEventType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlayerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, eventType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPlayerNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, connection_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAddressBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, port_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, numOfPlayers_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, success_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getMessageBytes());
      }
      for (int i = 0; i < statuses_.size(); i++) {
        output.writeBool(9, statuses_.get(i));
      }
      for (int i = 0; i < names_.size(); i++) {
        output.writeBytes(10, names_.getByteString(i));
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(11, finished_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBool(12, gameInProgress_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(13, getTileBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(14, row_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(15, column_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(16, rotation_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(17, meeple_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt32(18, position_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBool(19, shield_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeBytes(20, getTargetBytes());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeInt32(21, points_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        output.writeInt32(22, followers_);
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        output.writeInt32(23, targetIndex_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, eventType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPlayerNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, connection_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAddressBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, port_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, numOfPlayers_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, success_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getMessageBytes());
      }
      {
        int dataSize = 0;
        dataSize = 1 * getStatusesList().size();
        size += dataSize;
        size += 1 * getStatusesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < names_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(names_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getNamesList().size();
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, finished_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, gameInProgress_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getTileBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, row_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, column_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, rotation_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, meeple_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, position_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(19, shield_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, getTargetBytes());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(21, points_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(22, followers_);
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(23, targetIndex_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.carleton.comp4905.carcassonne.common.EventMessage.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.carleton.comp4905.carcassonne.common.EventMessage.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.carleton.comp4905.carcassonne.common.EventMessage.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.carleton.comp4905.carcassonne.common.EventMessage.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.carleton.comp4905.carcassonne.common.EventMessage.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.carleton.comp4905.carcassonne.common.EventMessage.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.carleton.comp4905.carcassonne.common.EventMessage.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.carleton.comp4905.carcassonne.common.EventMessage.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.carleton.comp4905.carcassonne.common.EventMessage.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.carleton.comp4905.carcassonne.common.EventMessage.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.carleton.comp4905.carcassonne.common.EventMessage.Event prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.carleton.comp4905.carcassonne.common.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.carleton.comp4905.carcassonne.common.EventMessage.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.carleton.comp4905.carcassonne.common.EventMessage.internal_static_edu_carleton_comp4905_carcassonne_common_Event_descriptor;
      }

      @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.carleton.comp4905.carcassonne.common.EventMessage.internal_static_edu_carleton_comp4905_carcassonne_common_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.carleton.comp4905.carcassonne.common.EventMessage.Event.class, edu.carleton.comp4905.carcassonne.common.EventMessage.Event.Builder.class);
      }

      // Construct using edu.carleton.comp4905.carcassonne.common.EventMessage.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      @Override
	public Builder clear() {
        super.clear();
        eventType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        playerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        connection_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        numOfPlayers_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        statuses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        finished_ = false;
        bitField0_ = (bitField0_ & ~0x00000400);
        gameInProgress_ = false;
        bitField0_ = (bitField0_ & ~0x00000800);
        tile_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        row_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        column_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        rotation_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        meeple_ = 0;
        bitField0_ = (bitField0_ & ~0x00010000);
        position_ = 0;
        bitField0_ = (bitField0_ & ~0x00020000);
        shield_ = false;
        bitField0_ = (bitField0_ & ~0x00040000);
        target_ = "";
        bitField0_ = (bitField0_ & ~0x00080000);
        points_ = 0;
        bitField0_ = (bitField0_ & ~0x00100000);
        followers_ = 0;
        bitField0_ = (bitField0_ & ~0x00200000);
        targetIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00400000);
        return this;
      }

      @Override
	public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.carleton.comp4905.carcassonne.common.EventMessage.internal_static_edu_carleton_comp4905_carcassonne_common_Event_descriptor;
      }

      @Override
	public edu.carleton.comp4905.carcassonne.common.EventMessage.Event getDefaultInstanceForType() {
        return edu.carleton.comp4905.carcassonne.common.EventMessage.Event.getDefaultInstance();
      }

      @Override
	public edu.carleton.comp4905.carcassonne.common.EventMessage.Event build() {
        edu.carleton.comp4905.carcassonne.common.EventMessage.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
	public edu.carleton.comp4905.carcassonne.common.EventMessage.Event buildPartial() {
        edu.carleton.comp4905.carcassonne.common.EventMessage.Event result = new edu.carleton.comp4905.carcassonne.common.EventMessage.Event(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.eventType_ = eventType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.playerName_ = playerName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.connection_ = connection_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.numOfPlayers_ = numOfPlayers_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.success_ = success_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.message_ = message_;
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          statuses_ = java.util.Collections.unmodifiableList(statuses_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.statuses_ = statuses_;
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          names_ = new com.google.protobuf.UnmodifiableLazyStringList(
              names_);
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.names_ = names_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000100;
        }
        result.finished_ = finished_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000200;
        }
        result.gameInProgress_ = gameInProgress_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00000400;
        }
        result.tile_ = tile_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00000800;
        }
        result.row_ = row_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.column_ = column_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.rotation_ = rotation_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.meeple_ = meeple_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.position_ = position_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.shield_ = shield_;
        if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.target_ = target_;
        if (((from_bitField0_ & 0x00100000) == 0x00100000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.points_ = points_;
        if (((from_bitField0_ & 0x00200000) == 0x00200000)) {
          to_bitField0_ |= 0x00080000;
        }
        result.followers_ = followers_;
        if (((from_bitField0_ & 0x00400000) == 0x00400000)) {
          to_bitField0_ |= 0x00100000;
        }
        result.targetIndex_ = targetIndex_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.carleton.comp4905.carcassonne.common.EventMessage.Event) {
          return mergeFrom((edu.carleton.comp4905.carcassonne.common.EventMessage.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.carleton.comp4905.carcassonne.common.EventMessage.Event other) {
        if (other == edu.carleton.comp4905.carcassonne.common.EventMessage.Event.getDefaultInstance()) return this;
        if (other.hasEventType()) {
          setEventType(other.getEventType());
        }
        if (other.hasPlayerName()) {
          bitField0_ |= 0x00000002;
          playerName_ = other.playerName_;
          onChanged();
        }
        if (other.hasConnection()) {
          setConnection(other.getConnection());
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000008;
          address_ = other.address_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasNumOfPlayers()) {
          setNumOfPlayers(other.getNumOfPlayers());
        }
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000080;
          message_ = other.message_;
          onChanged();
        }
        if (!other.statuses_.isEmpty()) {
          if (statuses_.isEmpty()) {
            statuses_ = other.statuses_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureStatusesIsMutable();
            statuses_.addAll(other.statuses_);
          }
          onChanged();
        }
        if (!other.names_.isEmpty()) {
          if (names_.isEmpty()) {
            names_ = other.names_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureNamesIsMutable();
            names_.addAll(other.names_);
          }
          onChanged();
        }
        if (other.hasFinished()) {
          setFinished(other.getFinished());
        }
        if (other.hasGameInProgress()) {
          setGameInProgress(other.getGameInProgress());
        }
        if (other.hasTile()) {
          bitField0_ |= 0x00001000;
          tile_ = other.tile_;
          onChanged();
        }
        if (other.hasRow()) {
          setRow(other.getRow());
        }
        if (other.hasColumn()) {
          setColumn(other.getColumn());
        }
        if (other.hasRotation()) {
          setRotation(other.getRotation());
        }
        if (other.hasMeeple()) {
          setMeeple(other.getMeeple());
        }
        if (other.hasPosition()) {
          setPosition(other.getPosition());
        }
        if (other.hasShield()) {
          setShield(other.getShield());
        }
        if (other.hasTarget()) {
          bitField0_ |= 0x00080000;
          target_ = other.target_;
          onChanged();
        }
        if (other.hasPoints()) {
          setPoints(other.getPoints());
        }
        if (other.hasFollowers()) {
          setFollowers(other.getFollowers());
        }
        if (other.hasTargetIndex()) {
          setTargetIndex(other.getTargetIndex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      @Override
	public final boolean isInitialized() {
        if (!hasEventType()) {
          
          return false;
        }
        if (!hasPlayerName()) {
          
          return false;
        }
        return true;
      }

      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.carleton.comp4905.carcassonne.common.EventMessage.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.carleton.comp4905.carcassonne.common.EventMessage.Event) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 eventType = 1;
      private int eventType_ ;
      /**
       * <code>required int32 eventType = 1;</code>
       */
      @Override
	public boolean hasEventType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 eventType = 1;</code>
       */
      @Override
	public int getEventType() {
        return eventType_;
      }
      /**
       * <code>required int32 eventType = 1;</code>
       */
      public Builder setEventType(int value) {
        bitField0_ |= 0x00000001;
        eventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 eventType = 1;</code>
       */
      public Builder clearEventType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        eventType_ = 0;
        onChanged();
        return this;
      }

      // required string playerName = 2;
      private java.lang.Object playerName_ = "";
      /**
       * <code>required string playerName = 2;</code>
       */
      @Override
	public boolean hasPlayerName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string playerName = 2;</code>
       */
      @Override
	public java.lang.String getPlayerName() {
        java.lang.Object ref = playerName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          playerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string playerName = 2;</code>
       */
      @Override
	public com.google.protobuf.ByteString
          getPlayerNameBytes() {
        java.lang.Object ref = playerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string playerName = 2;</code>
       */
      public Builder setPlayerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        playerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string playerName = 2;</code>
       */
      public Builder clearPlayerName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        playerName_ = getDefaultInstance().getPlayerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string playerName = 2;</code>
       */
      public Builder setPlayerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        playerName_ = value;
        onChanged();
        return this;
      }

      // optional bytes connection = 3;
      private com.google.protobuf.ByteString connection_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes connection = 3;</code>
       */
      @Override
	public boolean hasConnection() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes connection = 3;</code>
       */
      @Override
	public com.google.protobuf.ByteString getConnection() {
        return connection_;
      }
      /**
       * <code>optional bytes connection = 3;</code>
       */
      public Builder setConnection(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        connection_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes connection = 3;</code>
       */
      public Builder clearConnection() {
        bitField0_ = (bitField0_ & ~0x00000004);
        connection_ = getDefaultInstance().getConnection();
        onChanged();
        return this;
      }

      // optional string address = 4;
      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 4;</code>
       */
      @Override
	public boolean hasAddress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string address = 4;</code>
       */
      @Override
	public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 4;</code>
       */
      @Override
	public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 4;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 4;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000008);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 4;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        address_ = value;
        onChanged();
        return this;
      }

      // optional int32 port = 5;
      private int port_ ;
      /**
       * <code>optional int32 port = 5;</code>
       */
      @Override
	public boolean hasPort() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 port = 5;</code>
       */
      @Override
	public int getPort() {
        return port_;
      }
      /**
       * <code>optional int32 port = 5;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000010;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 port = 5;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000010);
        port_ = 0;
        onChanged();
        return this;
      }

      // optional int32 numOfPlayers = 6;
      private int numOfPlayers_ ;
      /**
       * <code>optional int32 numOfPlayers = 6;</code>
       */
      @Override
	public boolean hasNumOfPlayers() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 numOfPlayers = 6;</code>
       */
      @Override
	public int getNumOfPlayers() {
        return numOfPlayers_;
      }
      /**
       * <code>optional int32 numOfPlayers = 6;</code>
       */
      public Builder setNumOfPlayers(int value) {
        bitField0_ |= 0x00000020;
        numOfPlayers_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 numOfPlayers = 6;</code>
       */
      public Builder clearNumOfPlayers() {
        bitField0_ = (bitField0_ & ~0x00000020);
        numOfPlayers_ = 0;
        onChanged();
        return this;
      }

      // optional bool success = 7;
      private boolean success_ ;
      /**
       * <code>optional bool success = 7;</code>
       */
      @Override
	public boolean hasSuccess() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool success = 7;</code>
       */
      @Override
	public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>optional bool success = 7;</code>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000040;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool success = 7;</code>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000040);
        success_ = false;
        onChanged();
        return this;
      }

      // optional string message = 8;
      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 8;</code>
       */
      @Override
	public boolean hasMessage() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string message = 8;</code>
       */
      @Override
	public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 8;</code>
       */
      @Override
	public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 8;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 8;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000080);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 8;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        message_ = value;
        onChanged();
        return this;
      }

      // repeated bool statuses = 9;
      private java.util.List<java.lang.Boolean> statuses_ = java.util.Collections.emptyList();
      private void ensureStatusesIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          statuses_ = new java.util.ArrayList<java.lang.Boolean>(statuses_);
          bitField0_ |= 0x00000100;
         }
      }
      /**
       * <code>repeated bool statuses = 9;</code>
       */
      @Override
	public java.util.List<java.lang.Boolean>
          getStatusesList() {
        return java.util.Collections.unmodifiableList(statuses_);
      }
      /**
       * <code>repeated bool statuses = 9;</code>
       */
      @Override
	public int getStatusesCount() {
        return statuses_.size();
      }
      /**
       * <code>repeated bool statuses = 9;</code>
       */
      @Override
	public boolean getStatuses(int index) {
        return statuses_.get(index);
      }
      /**
       * <code>repeated bool statuses = 9;</code>
       */
      public Builder setStatuses(
          int index, boolean value) {
        ensureStatusesIsMutable();
        statuses_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool statuses = 9;</code>
       */
      public Builder addStatuses(boolean value) {
        ensureStatusesIsMutable();
        statuses_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool statuses = 9;</code>
       */
      public Builder addAllStatuses(
          java.lang.Iterable<? extends java.lang.Boolean> values) {
        ensureStatusesIsMutable();
        super.addAll(values, statuses_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool statuses = 9;</code>
       */
      public Builder clearStatuses() {
        statuses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }

      // repeated string names = 10;
      private com.google.protobuf.LazyStringList names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNamesIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          names_ = new com.google.protobuf.LazyStringArrayList(names_);
          bitField0_ |= 0x00000200;
         }
      }
      /**
       * <code>repeated string names = 10;</code>
       */
      @Override
	public java.util.List<java.lang.String>
          getNamesList() {
        return java.util.Collections.unmodifiableList(names_);
      }
      /**
       * <code>repeated string names = 10;</code>
       */
      @Override
	public int getNamesCount() {
        return names_.size();
      }
      /**
       * <code>repeated string names = 10;</code>
       */
      @Override
	public java.lang.String getNames(int index) {
        return names_.get(index);
      }
      /**
       * <code>repeated string names = 10;</code>
       */
      @Override
	public com.google.protobuf.ByteString
          getNamesBytes(int index) {
        return names_.getByteString(index);
      }
      /**
       * <code>repeated string names = 10;</code>
       */
      public Builder setNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNamesIsMutable();
        names_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names = 10;</code>
       */
      public Builder addNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNamesIsMutable();
        names_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names = 10;</code>
       */
      public Builder addAllNames(
          java.lang.Iterable<java.lang.String> values) {
        ensureNamesIsMutable();
        super.addAll(values, names_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names = 10;</code>
       */
      public Builder clearNames() {
        names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names = 10;</code>
       */
      public Builder addNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNamesIsMutable();
        names_.add(value);
        onChanged();
        return this;
      }

      // optional bool finished = 11;
      private boolean finished_ ;
      /**
       * <code>optional bool finished = 11;</code>
       */
      @Override
	public boolean hasFinished() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional bool finished = 11;</code>
       */
      @Override
	public boolean getFinished() {
        return finished_;
      }
      /**
       * <code>optional bool finished = 11;</code>
       */
      public Builder setFinished(boolean value) {
        bitField0_ |= 0x00000400;
        finished_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool finished = 11;</code>
       */
      public Builder clearFinished() {
        bitField0_ = (bitField0_ & ~0x00000400);
        finished_ = false;
        onChanged();
        return this;
      }

      // optional bool gameInProgress = 12;
      private boolean gameInProgress_ ;
      /**
       * <code>optional bool gameInProgress = 12;</code>
       */
      @Override
	public boolean hasGameInProgress() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional bool gameInProgress = 12;</code>
       */
      @Override
	public boolean getGameInProgress() {
        return gameInProgress_;
      }
      /**
       * <code>optional bool gameInProgress = 12;</code>
       */
      public Builder setGameInProgress(boolean value) {
        bitField0_ |= 0x00000800;
        gameInProgress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool gameInProgress = 12;</code>
       */
      public Builder clearGameInProgress() {
        bitField0_ = (bitField0_ & ~0x00000800);
        gameInProgress_ = false;
        onChanged();
        return this;
      }

      // optional string tile = 13;
      private java.lang.Object tile_ = "";
      /**
       * <code>optional string tile = 13;</code>
       */
      @Override
	public boolean hasTile() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional string tile = 13;</code>
       */
      @Override
	public java.lang.String getTile() {
        java.lang.Object ref = tile_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tile = 13;</code>
       */
      @Override
	public com.google.protobuf.ByteString
          getTileBytes() {
        java.lang.Object ref = tile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tile = 13;</code>
       */
      public Builder setTile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        tile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tile = 13;</code>
       */
      public Builder clearTile() {
        bitField0_ = (bitField0_ & ~0x00001000);
        tile_ = getDefaultInstance().getTile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tile = 13;</code>
       */
      public Builder setTileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        tile_ = value;
        onChanged();
        return this;
      }

      // optional int32 row = 14;
      private int row_ ;
      /**
       * <code>optional int32 row = 14;</code>
       */
      @Override
	public boolean hasRow() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional int32 row = 14;</code>
       */
      @Override
	public int getRow() {
        return row_;
      }
      /**
       * <code>optional int32 row = 14;</code>
       */
      public Builder setRow(int value) {
        bitField0_ |= 0x00002000;
        row_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 row = 14;</code>
       */
      public Builder clearRow() {
        bitField0_ = (bitField0_ & ~0x00002000);
        row_ = 0;
        onChanged();
        return this;
      }

      // optional int32 column = 15;
      private int column_ ;
      /**
       * <code>optional int32 column = 15;</code>
       */
      @Override
	public boolean hasColumn() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional int32 column = 15;</code>
       */
      @Override
	public int getColumn() {
        return column_;
      }
      /**
       * <code>optional int32 column = 15;</code>
       */
      public Builder setColumn(int value) {
        bitField0_ |= 0x00004000;
        column_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 column = 15;</code>
       */
      public Builder clearColumn() {
        bitField0_ = (bitField0_ & ~0x00004000);
        column_ = 0;
        onChanged();
        return this;
      }

      // optional int32 rotation = 16;
      private int rotation_ ;
      /**
       * <code>optional int32 rotation = 16;</code>
       */
      @Override
	public boolean hasRotation() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional int32 rotation = 16;</code>
       */
      @Override
	public int getRotation() {
        return rotation_;
      }
      /**
       * <code>optional int32 rotation = 16;</code>
       */
      public Builder setRotation(int value) {
        bitField0_ |= 0x00008000;
        rotation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rotation = 16;</code>
       */
      public Builder clearRotation() {
        bitField0_ = (bitField0_ & ~0x00008000);
        rotation_ = 0;
        onChanged();
        return this;
      }

      // optional int32 meeple = 17;
      private int meeple_ ;
      /**
       * <code>optional int32 meeple = 17;</code>
       */
      @Override
	public boolean hasMeeple() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional int32 meeple = 17;</code>
       */
      @Override
	public int getMeeple() {
        return meeple_;
      }
      /**
       * <code>optional int32 meeple = 17;</code>
       */
      public Builder setMeeple(int value) {
        bitField0_ |= 0x00010000;
        meeple_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 meeple = 17;</code>
       */
      public Builder clearMeeple() {
        bitField0_ = (bitField0_ & ~0x00010000);
        meeple_ = 0;
        onChanged();
        return this;
      }

      // optional int32 position = 18;
      private int position_ ;
      /**
       * <code>optional int32 position = 18;</code>
       */
      @Override
	public boolean hasPosition() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <code>optional int32 position = 18;</code>
       */
      @Override
	public int getPosition() {
        return position_;
      }
      /**
       * <code>optional int32 position = 18;</code>
       */
      public Builder setPosition(int value) {
        bitField0_ |= 0x00020000;
        position_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 position = 18;</code>
       */
      public Builder clearPosition() {
        bitField0_ = (bitField0_ & ~0x00020000);
        position_ = 0;
        onChanged();
        return this;
      }

      // optional bool shield = 19;
      private boolean shield_ ;
      /**
       * <code>optional bool shield = 19;</code>
       */
      @Override
	public boolean hasShield() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      /**
       * <code>optional bool shield = 19;</code>
       */
      @Override
	public boolean getShield() {
        return shield_;
      }
      /**
       * <code>optional bool shield = 19;</code>
       */
      public Builder setShield(boolean value) {
        bitField0_ |= 0x00040000;
        shield_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool shield = 19;</code>
       */
      public Builder clearShield() {
        bitField0_ = (bitField0_ & ~0x00040000);
        shield_ = false;
        onChanged();
        return this;
      }

      // optional string target = 20;
      private java.lang.Object target_ = "";
      /**
       * <code>optional string target = 20;</code>
       */
      @Override
	public boolean hasTarget() {
        return ((bitField0_ & 0x00080000) == 0x00080000);
      }
      /**
       * <code>optional string target = 20;</code>
       */
      @Override
	public java.lang.String getTarget() {
        java.lang.Object ref = target_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          target_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string target = 20;</code>
       */
      @Override
	public com.google.protobuf.ByteString
          getTargetBytes() {
        java.lang.Object ref = target_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          target_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string target = 20;</code>
       */
      public Builder setTarget(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00080000;
        target_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string target = 20;</code>
       */
      public Builder clearTarget() {
        bitField0_ = (bitField0_ & ~0x00080000);
        target_ = getDefaultInstance().getTarget();
        onChanged();
        return this;
      }
      /**
       * <code>optional string target = 20;</code>
       */
      public Builder setTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00080000;
        target_ = value;
        onChanged();
        return this;
      }

      // optional int32 points = 21;
      private int points_ ;
      /**
       * <code>optional int32 points = 21;</code>
       */
      @Override
	public boolean hasPoints() {
        return ((bitField0_ & 0x00100000) == 0x00100000);
      }
      /**
       * <code>optional int32 points = 21;</code>
       */
      @Override
	public int getPoints() {
        return points_;
      }
      /**
       * <code>optional int32 points = 21;</code>
       */
      public Builder setPoints(int value) {
        bitField0_ |= 0x00100000;
        points_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 points = 21;</code>
       */
      public Builder clearPoints() {
        bitField0_ = (bitField0_ & ~0x00100000);
        points_ = 0;
        onChanged();
        return this;
      }

      // optional int32 followers = 22;
      private int followers_ ;
      /**
       * <code>optional int32 followers = 22;</code>
       */
      @Override
	public boolean hasFollowers() {
        return ((bitField0_ & 0x00200000) == 0x00200000);
      }
      /**
       * <code>optional int32 followers = 22;</code>
       */
      @Override
	public int getFollowers() {
        return followers_;
      }
      /**
       * <code>optional int32 followers = 22;</code>
       */
      public Builder setFollowers(int value) {
        bitField0_ |= 0x00200000;
        followers_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 followers = 22;</code>
       */
      public Builder clearFollowers() {
        bitField0_ = (bitField0_ & ~0x00200000);
        followers_ = 0;
        onChanged();
        return this;
      }

      // optional int32 targetIndex = 23;
      private int targetIndex_ ;
      /**
       * <code>optional int32 targetIndex = 23;</code>
       */
      @Override
	public boolean hasTargetIndex() {
        return ((bitField0_ & 0x00400000) == 0x00400000);
      }
      /**
       * <code>optional int32 targetIndex = 23;</code>
       */
      @Override
	public int getTargetIndex() {
        return targetIndex_;
      }
      /**
       * <code>optional int32 targetIndex = 23;</code>
       */
      public Builder setTargetIndex(int value) {
        bitField0_ |= 0x00400000;
        targetIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 targetIndex = 23;</code>
       */
      public Builder clearTargetIndex() {
        bitField0_ = (bitField0_ & ~0x00400000);
        targetIndex_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:edu.carleton.comp4905.carcassonne.common.Event)
    }

    static {
      defaultInstance = new Event(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:edu.carleton.comp4905.carcassonne.common.Event)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_carleton_comp4905_carcassonne_common_Event_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_carleton_comp4905_carcassonne_common_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013event.proto\022(edu.carleton.comp4905.car" +
      "cassonne.common\"\233\003\n\005Event\022\021\n\teventType\030\001" +
      " \002(\005\022\022\n\nplayerName\030\002 \002(\t\022\022\n\nconnection\030\003" +
      " \001(\014\022\017\n\007address\030\004 \001(\t\022\014\n\004port\030\005 \001(\005\022\024\n\014n" +
      "umOfPlayers\030\006 \001(\005\022\017\n\007success\030\007 \001(\010\022\017\n\007me" +
      "ssage\030\010 \001(\t\022\020\n\010statuses\030\t \003(\010\022\r\n\005names\030\n" +
      " \003(\t\022\020\n\010finished\030\013 \001(\010\022\026\n\016gameInProgress" +
      "\030\014 \001(\010\022\014\n\004tile\030\r \001(\t\022\013\n\003row\030\016 \001(\005\022\016\n\006col" +
      "umn\030\017 \001(\005\022\020\n\010rotation\030\020 \001(\005\022\016\n\006meeple\030\021 " +
      "\001(\005\022\020\n\010position\030\022 \001(\005\022\016\n\006shield\030\023 \001(\010\022\016\n",
      "\006target\030\024 \001(\t\022\016\n\006points\030\025 \001(\005\022\021\n\tfollowe" +
      "rs\030\026 \001(\005\022\023\n\013targetIndex\030\027 \001(\005B\016B\014EventMe" +
      "ssage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        @Override
		public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_carleton_comp4905_carcassonne_common_Event_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_carleton_comp4905_carcassonne_common_Event_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_carleton_comp4905_carcassonne_common_Event_descriptor,
              new java.lang.String[] { "EventType", "PlayerName", "Connection", "Address", "Port", "NumOfPlayers", "Success", "Message", "Statuses", "Names", "Finished", "GameInProgress", "Tile", "Row", "Column", "Rotation", "Meeple", "Position", "Shield", "Target", "Points", "Followers", "TargetIndex", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
