package edu.carleton.comp4905.carcassonne.common;

public enum Position {
	TOP_LEFT_LEFT, TOP_LEFT, TOP_LEFT_TOP,
	TOP,
	TOP_RIGHT_TOP, TOP_RIGHT, TOP_RIGHT_RIGHT,
	LEFT, CENTER, RIGHT,
	BOTTOM_LEFT_LEFT, BOTTOM_LEFT, BOTTOM_LEFT_BOTTOM,
	BOTTOM,
	BOTTOM_RIGHT_BOTTOM, BOTTOM_RIGHT, BOTTOM_RIGHT_RIGHT
}
